import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import express from "express";
import { z } from "zod";

const CONFIG={githubToken:process.env.GITHUB_TOKEN||"",allowedRepos:(process.env.ALLOWED_REPOSITORIES||"").split(",").map(s=>s.trim()).filter(Boolean),allowDirectMain:process.env.ALLOW_DIRECT_MAIN_PUSH==="true"};
function validateRepo(o,r){const fn=`${o}/${r}`;if(!CONFIG.allowedRepos.includes(fn))throw new Error(`Repo not allowed: ${fn}`)}
function validatePath(p){if(p.includes(".."))throw new Error("Traversal");if(p.startsWith("/"))throw new Error("Absolute")}
function sl(m){return m.replace(/ghp_[a-zA-Z0-9]{36,}/g,"***").replace(/github_pat_[a-zA-Z0-9_]{36,}/g,"***")}

class GH{constructor(t){this.t=t;this.b="https://api.github.com"}
async rq(m,p,b=null){if(!this.t)throw new Error("No token");const h={Authorization:`Bearer ${this.t}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","User-Agent":"gpt-github-bridge/1.0"};const o={method:m,headers:h};if(b){o.headers["Content-Type"]="application/json";o.body=JSON.stringify(b)}const r=await fetch(`${this.b}${p}`,o);const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={message:t}};if(!r.ok){const e=new Error(`GH ${r.status}: ${d.message||t}`);e.s=r.status;e.m=d.message;throw e}return{s:r.status,d}}
async repo(o,r){const{d}=await this.rq("GET",`/repos/${o}/${r}`);return{fn:d.full_name,db:d.default_branch,pm:d.permissions}}
async ref(o,r,f){const{d}=await this.rq("GET",`/repos/${o}/${r}/git/ref/${encodeURIComponent(f)}`);return{ref:d.ref,sha:d.object.sha}}
async content(o,r,p,f){try{const q=f?`?ref=${encodeURIComponent(f)}`:'';const{d}=await this.rq("GET",`/repos/${o}/${r}/contents/${p}${q}`);return{path:d.path,sha:d.sha,size:d.size,content:d.content?Buffer.from(d.content,"base64").toString("utf-8"):null,exists:true}}catch(e){if(e.s===404)return{path:p,sha:null,size:0,content:null,exists:false};throw e}}
async branch(o,r,b,s){const{d}=await this.rq("POST",`/repos/${o}/${r}/git/refs`,{ref:`refs/heads/${b}`,sha:s});return{ref:d.ref,sha:d.object.sha}}
async file(o,r,b,p,c,m,s=null){const bd={message:m,content:Buffer.from(c,"utf-8").toString("base64"),branch:b};if(s)bd.sha=s;const{d}=await this.rq("PUT",`/repos/${o}/${r}/contents/${p}`,bd);return{path:d.content.path,sha:d.content.sha,csha:d.commit.sha,curl:d.commit.html_url}}
async pr(o,r,h,b,t,bd,dr=true){const{d}=await this.rq("POST",`/repos/${o}/${r}/pulls`,{title:t,head:h,base:b,body:bd,draft:dr});return{num:d.number,url:d.html_url,st:d.state,dr:d.draft,head:d.head.ref,base:d.base.ref}}}

function createServer(){const gh=new GH(CONFIG.githubToken);const s=new McpServer({name:"gpt-github-bridge",version:"1.0.0"},{capabilities:{tools:{}}});
s.tool("get_repository","Get GitHub repo metadata",{owner:z.string(),repo:z.string()},async({owner,repo})=>{validateRepo(owner,repo);const i=await gh.repo(owner,repo);const mr=await gh.ref(owner,repo,`heads/${i.db}`);return{content:[{type:"text",text:JSON.stringify({...i,latestCommitSha:mr.sha,writable:true,prEnabled:true},null,2)}]}});
s.tool("read_file","Read a file from GitHub",{owner:z.string(),repo:z.string(),path:z.string(),ref:z.string().optional()},async({owner,repo,path,ref})=>{validateRepo(owner,repo);validatePath(path);const r=await gh.content(owner,repo,path,ref);const d=r.content&&r.content.length>10000?r.content.substring(0,10000)+`...(truncated ${r.content.length} chars)`:r.content;return{content:[{type:"text",text:JSON.stringify({...r,content:d},null,2)}]}});
s.tool("create_branch","Create a new branch",{owner:z.string(),repo:z.string(),branch:z.string(),base:z.string().optional()},async({owner,repo,branch,base})=>{validateRepo(owner,repo);const i=await gh.repo(owner,repo);const bb=base||i.db;const br=await gh.ref(owner,repo,`heads/${bb}`);const r=await gh.branch(owner,repo,branch,br.sha);return{content:[{type:"text",text:JSON.stringify({success:true,repo:`${owner}/${repo}`,branch,base:bb,sha:r.sha},null,2)}]}});
s.tool("upsert_file","Create/update file on a feature branch",{owner:z.string(),repo:z.string(),branch:z.string(),path:z.string(),content:z.string(),commit_message:z.string(),expected_sha:z.string().nullable().optional()},async({owner,repo,branch,path,content,commit_message,expected_sha})=>{validateRepo(owner,repo);validatePath(path);if(!CONFIG.allowDirectMain){const i=await gh.repo(owner,repo);if(branch===i.db)throw new Error(`Direct push to '${branch}' blocked`)}let s=expected_sha||null;if(!s){const e=await gh.content(owner,repo,path,branch);if(e.exists)s=e.sha}const r=await gh.file(owner,repo,branch,path,content,commit_message,s);return{content:[{type:"text",text:JSON.stringify({success:true,path:r.path,commitSha:r.csha,commitUrl:r.curl,op:s?"updated":"created"},null,2)}]}});
s.tool("create_pull_request","Create a Draft PR",{owner:z.string(),repo:z.string(),head:z.string(),base:z.string(),title:z.string(),body:z.string(),draft:z.boolean().optional()},async({owner,repo,head,base,title,body,draft=true})=>{validateRepo(owner,repo);const r=await gh.pr(owner,repo,head,base,title,body,draft);return{content:[{type:"text",text:JSON.stringify({success:true,...r},null,2)}]}});
s.tool("publish_skill","ONE-CLICK: branch + files + Draft PR",{owner:z.string(),repo:z.string(),skill_name:z.string(),files:z.array(z.object({path:z.string(),content:z.string()})),commit_message:z.string().optional(),pr_title:z.string().optional(),pr_body:z.string().optional(),target_directory:z.string().optional()},async({owner,repo,skill_name,files,commit_message,pr_title,pr_body,target_directory})=>{validateRepo(owner,repo);if(!files||!files.length)throw new Error("Need files");if(files.length>50)throw new Error("Max 50");files.forEach(f=>validatePath(f.path));const i=await gh.repo(owner,repo);const br=await gh.ref(owner,repo,`heads/${i.db}`);const ts=new Date().toISOString().replace(/[-:]/g,"").replace(/\..+/,"").replace("T","-");const bn=`gpt/upload-${skill_name}-${ts}`;let bc=false,cs=null;const cf=[],st=[];try{await gh.branch(owner,repo,bn,br.sha);bc=true;st.push({step:"branch",status:"ok",branch:bn});for(const f of files){const fp=target_directory?`${target_directory.replace(/\/$/,"")}/${f.path}`:f.path;const r=await gh.file(owner,repo,bn,fp,f.content,commit_message||`Upload ${skill_name}: ${f.path}`,null);cs=r.csha;cf.push(fp);st.push({step:"file",status:"ok",path:fp,sha:r.sha})}const pr=await gh.pr(owner,repo,bn,i.db,pr_title||`[GPT] Upload ${skill_name}`,pr_body||`Uploaded via gpt-github-bridge.`,true);st.push({step:"pr",status:"ok",prNum:pr.num});return{content:[{type:"text",text:JSON.stringify({success:true,repo:`${owner}/${repo}`,branch:bn,commitSha:cs,prNumber:pr.num,prUrl:pr.url,changedFiles:cf,steps:st},null,2)}]}}catch(err){return{content:[{type:"text",text:JSON.stringify({success:false,failedStep:st[st.length-1]?.step||"branch",ghStatus:err.s,ghMessage:err.m||err.message,completedSteps:st,retryable:err.s!==422},null,2)}],isError:true}}});
return s;}

const app=express();app.use(express.json());

app.get("/health",(_req,res)=>res.json({status:"ok",service:"gpt-github-bridge",version:"1.0.0",allowedRepos:CONFIG.allowedRepos,hasToken:!!CONFIG.githubToken}));

app.post("/mcp",async(req,res)=>{try{const transport=new StreamableHTTPServerTransport({sessionIdGenerator:()=>crypto.randomUUID()});const server=createServer();await server.connect(transport);await transport.handleRequest(req,res,req.body)}catch(e){console.error("[MCP]",sl(e.message));if(!res.headersSent)res.status(500).json({jsonrpc:"2.0",error:{code:-32603,message:"Internal error"},id:req.body?.id||null})}});

app.get("/mcp",async(req,res)=>{try{const transport=new StreamableHTTPServerTransport({sessionIdGenerator:()=>crypto.randomUUID()});const server=createServer();await server.connect(transport);await transport.handleRequest(req,res)}catch(e){console.error("[MCP GET]",sl(e.message));if(!res.headersSent)res.status(500).json({jsonrpc:"2.0",error:{code:-32603,message:"Internal error"},id:null})}});

const PORT=process.env.PORT||3000;
app.listen(PORT,()=>console.log(`Bridge ${PORT}, token:${!!CONFIG.githubToken}`));
export default app;